#
# Build with:
#
# docker build -t jnidzwetzki/mysql-ha-cloud:stable -f Dockerfile-mysql .
#
#################

FROM mysql:8.0.21

SHELL ["/bin/bash", "-c"]
WORKDIR /mycm
COPY ./cluster_manager cluster_manager

RUN \
    apt-get update && \
    apt-get upgrade -y && \
    # \
    # Install system basics \
    # \
    apt-get install -y unzip curl wget gnupg2 lsb-release && \
    # \
    # Install percona XtraBackup \
    # \
    apt-get install -y libdbd-mysql-perl libcurl4-openssl-dev rsync libev4 && \
    wget https://www.percona.com/downloads/Percona-XtraBackup-LATEST/Percona-XtraBackup-8.0.14/binary/debian/buster/x86_64/percona-xtrabackup-80_8.0.14-1.buster_amd64.deb -O /tmp/xtrabackup.deb && \ 
    dpkg -i /tmp/xtrabackup.deb && \
    rm /tmp/xtrabackup.deb && \
    # \
    # Install consul \
    # \
    wget https://releases.hashicorp.com/consul/1.8.4/consul_1.8.4_linux_amd64.zip -O /tmp/consul.zip && \
    echo "220b0af8e439d2fe3fc7e1ca07bdbda1f3ee5b2fa889983c04e7004d99ade5ece005b45e1288bfcbe2bf847f23d35684845bd6edbf59fe4220be8e9e83f05439 /tmp/consul.zip" | sha512sum -c && \
    unzip /tmp/consul.zip -d /usr/local/bin && \
    rm /tmp/consul.zip && \
    # \
    # Install mysql cluster manager \
    # \
    apt-get install -y python3.7 python3.7-dev python3-venv python3.7-venv && \
    python3.7 -m venv venv && \
    source venv/bin/activate && \
    pip install -r cluster_manager/requirements.txt 
